### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by drojf** [07th-mod/ponscripter-umineko#1]
## General

- [ ] Add readme to this repo

## Build script

- [X] Test build script on disk first (as a python script), before trying real thing
- [ ] ~~Download from ponscripter-fork repo using https://github.com/marketplace/actions/release-downloader ~~
    - Ended up downloading from within python script 
- [X] Apply MacOS base image - this also applies the icon, see https://github.com/07th-mod/ponscripter-fork/pull/1/files
- [ ]  ~~Change out windows icon using rcedit? https://github.com/electron/rcedit ~~
    -  ~~Download from https://github.com/electron/rcedit/releases/latest/download/rcedit-x64.exe ~~
    -  ~~Call `rcedit-x64.exe a.exe --set-icon default.ico` ~~
    - **ended up using resource hacker instead**
- [X] Rename and duplicate executables (one for question, one for answer) as per https://github.com/07th-mod/ponscripter-fork/pull/1/files
- [X] Make sure build script setup to run on tag
- [ ] Add correct icon for answer arcs 

## Ponscripter-fork repo

- [ ] Check that releases still work on old repo, generate a new release, then test above build script
